---
title: "notes 09_07"
author: "Tess"
date: "9/7/2020"
output: html_document
---

select (surveys, month, plot_id, genus)
to select lists of things, can also do negative indexing, i.e.select (surveys, month, -plot_id, -genus)
read_csv command is the tidyverse way of reading in a csv file as a tibble instead of using the read.csv command to load it in a data frame
filter allows us to include or exclude data based on a certain criteria
ex. filter (surveys, year == 1991) - file name, the condition, the criteria
surveys_no91 <- filter (surveys, year != 1991) - name the filtered data to create data frame
surveys_weight <- select (surveys_no91, weight, genus) select certain criteria from that data frame 
pipe in tidyverse %>%  (control shift m)
ex:
surveys %>% 
+ filter (year == 1991) %>% 
+ select(genus, weight)
better than nesting, feed surveys into pipe, then filter into pipe then select - can consider the pipe to be a "then" ex: surveys THEN filter by year THEN select by columns
 when you're working with the pipes, a plus sign will follow on the next line, letting you know more input is needed
 surveys %>% 
 mutate(weight_kg = weight/1000) takes all the data in the weight column and divides them by 1000 and creates new column titled weight_kg, you can look at the bottom to see that the columns were added, or run select to have those exact columns fed back 
 ex: select (surveys_kg, weight_kg, weight_not_kg)
  surveys %>% 
+ filter (!is.na(weight)) %>% 
+ mutate (weight_kg/1000)  --- in order to filter out the na's in the weight column
surveys %>% 
+ group_by(sex) %>% 
+ summarize(mean_weight = mean (weight, na.rm = TRUE)) - na.rm is only removing na's from mean_weight column OR you could add in a filter function before the "group_by" function to remove all na's ex: 
filter (!is.na(sex)) ---will only take one at a time, cannot do !is.na(sex, mean_weight)
group_by is very flexible
print (n = ) allows you to look at X many rows
up key allows you to look at history of commands - called text buffer, cannot start in middle of a pipe, because R is not "remembering", so you have to start with the data frame you're working on 
"summarize" can be stacked on top of each other - see below 
surveys %>% 
+ filter (!is.na(weight)) %>% 
+ group_by (sex, species_id) %>% 
+ summarize (mean_weight = mean(weight, na.rm =TRUE),
+            min_weight =min (weight), 
+            max_weight = max (weight))
`summarise()` regrouping output by 'sex' (override with `.groups` argument)
# A tibble: 64 x
# Groups:   sex [3]
   sex   species_id mean_weight min_weight max_weight
sometimes you have to use n instead of count feature, especially when commands are stacked, ex: in the summarize above, stacked commands
   <chr> <chr>            <dbl>      <dbl>      <dbl>
 1 F     BA                9.16          6         18
 2 F     DM               41.6          10         66
 3 F     DO               48.5          12         76
 4 F     DS              118.           45        190
 5 F     NL              154.           32        274
 6 F     OL               31.1          10         56
 7 F     OT               24.8           5         46
 8 F     OX               21            20         22
 9 F     PB               30.2          12         54
10 F     PE               22.8          11         38

arrange feature will sort columns in ascending order ex: arrange(min_weight) 
cannot stack within arrange feature
count feature to tally up data from a column ex: 
surveys %>% 
+ count (sex)
# A tibble: 3 x 2
  sex       n
  <chr> <int>
1 F     15690
2 M     17348
3 NA     1748

OR by :
surveys %>% 
+ group_by(sex) %>% 
+ summarize (count = n())
`summarise()` ungrouping output (override with `.groups` argument)
# A tibble: 3 x 2
  sex   count
  <chr> <int>
1 F     15690
2 M     17348
3 NA     1748
count feature can be stacked